# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('support', models.FloatField()),
                ('confidence', models.FloatField()),
                ('found_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='arule',
            name='current_diseases',
            field=models.ManyToManyField(related_name='current_diseases', to='clalit.Disease'),
        ),
        migrations.AddField(
            model_name='arule',
            name='expected_diseases',
            field=models.ManyToManyField(related_name='expected_diseases', to='clalit.Disease'),
        ),
    ]
